#!/bin/bash
myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;

flag=0

#iplist="ip.txt"

wget --quiet -O iplist.txt https://raw.githubusercontent.com/cartoonn/openvpn-D7/master/ip.txt

#if [ -f iplist ]
#then

iplist="iplist.txt"

lines=`cat $iplist`
#echo $lines

for line in $lines; do
#        echo "$line"
        if [ "$line" = "$myip" ]
        then
                flag=1
        fi

done

echo

function create_user() {
	useradd -M $uname
	echo "$uname:$pass" | chpasswd
	usermod -e $expdate $uname

	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`;
	myip2="s/xxxxxxxxx/$myip/g";	
	wget -qO /tmp/client.ovpn "https://raw.githubusercontent.com/cartoonn/openvpn-D7/master/1194-client.ovpn"
	sed -i 's/remote xxxxxxxxx 1194/remote xxxxxxxxx 443/g' /tmp/client.ovpn
	sed -i $myip2 /tmp/client.ovpn
	echo ""
	echo "========================="
	echo "Host IP : $myip"
	echo "Port    : 443/22/80"
	echo "Squid   : 8080/3128"
	echo "========================="
	echo "Script by THIRD-VPN"
	echo "========================="
}

function renew_user() {
	echo "New expiration date for $uname: $expdate...";
	usermod -e $expdate $uname
}

function delete_user(){
	userdel $uname
}

function expired_users(){
	cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
	totalaccounts=`cat /tmp/expirelist.txt | wc -l`
	for((i=1; i<=$totalaccounts; i++ )); do
		tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
		username=`echo $tuserval | cut -f1 -d:`
		userexp=`echo $tuserval | cut -f2 -d:`
		userexpireinseconds=$(( $userexp * 86400 ))
		todaystime=`date +%s`
		if [ $userexpireinseconds -lt $todaystime ] ; then
			echo $username
		fi
	done
	rm /tmp/expirelist.txt
}

function not_expired_users(){
    cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
    totalaccounts=`cat /tmp/expirelist.txt | wc -l`
    for((i=1; i<=$totalaccounts; i++ )); do
        tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
        username=`echo $tuserval | cut -f1 -d:`
        userexp=`echo $tuserval | cut -f2 -d:`
        userexpireinseconds=$(( $userexp * 86400 ))
        todaystime=`date +%s`
        if [ $userexpireinseconds -gt $todaystime ] ; then
            echo $username
        fi
    done
	rm /tmp/expirelist.txt
}

function used_data(){
	myip=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0' | head -n1`
	myint=`ifconfig | grep -B1 "inet addr:$myip" | head -n1 | awk '{print $1}'`
	ifconfig $myint | grep "RX bytes" | sed -e 's/ *RX [a-z:0-9]*/Received: /g' | sed -e 's/TX [a-z:0-9]*/\nTransfered: /g'
}

	clear
	echo "--------------- ??????????????? Server - IP: $myip ---------------"
	cname=$( awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo )
	cores=$( awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo )
	freq=$( awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo )
	tram=$( free -m | awk 'NR==2 {print $2}' )
	swap=$( free -m | awk 'NR==4 {print $2}' )
	up=$(uptime|awk '{ $1=$2=$(NF-6)=$(NF-5)=$(NF-4)=$(NF-3)=$(NF-2)=$(NF-1)=$NF=""; print }')

	echo -e "\e[032;1mCPU model:\e[0m $cname"
	echo -e "\e[032;1mNumber of cores:\e[0m $cores"
	echo -e "\e[032;1mCPU frequency:\e[0m $freq MHz"
	echo -e "\e[032;1mTotal amount of ram:\e[0m $tram MB"
	echo -e "\e[032;1mTotal amount of swap:\e[0m $swap MB"
	echo -e "\e[032;1mSystem uptime:\e[0m $up"
	echo -e "\e[032;1mScript modify by:\e[0m THIRDl | "
	echo "------------------------------------------------------------------------------"
	echo "???????????????? SSH & OpenVPN????????????"
	echo -e "\e[031;1m 1\e[0m) ???????????????? SSH/OpenVPN (\e[34;1muser-add\e[0m)"
	echo -e "\e[031;1m 2\e[0m) ??????????????????????SSH/OpenVPN (\e[34;1muser-gen\e[0m)"
	echo -e "\e[031;1m 3\e[0m) ?????????????????? (\e[34;1muser-trial\e[0m)"
	echo -e "\e[031;1m 4\e[0m) ???????????????????? SSH/VPN (\e[34;1muser-pass\e[0m)"
	echo -e "\e[031;1m 5\e[0m) ???????????????????????? SSH/OpenVPN (\e[34;1muser-renew\e[0m)"
	echo -e "\e[031;1m 6\e[0m) ????????????? SSH/OpenVPN (\e[34;1muser-del\e[0m)"
	echo -e "\e[031;1m 7\e[0m) ??????????????? Dropbear & OpenSSH (\e[34;1muser-login\e[0m)"
	echo -e "\e[031;1m 8\e[0m) ????????????????????????????????? (\e[34;1mauto-limit\e[0m)"
	echo -e "\e[031;1m 9\e[0m) ????????????????????? SSH & OpenVPN (\e[34;1muser-detail\e[0m)"
	echo -e "\e[031;1m10\e[0m) ????????????????????????? (\e[34;1muser-list\e[0m)"
	echo -e "\e[031;1m11\e[0m) ?????????????? (\e[34;1mdelete-user-expire\e[0m)"
	echo -e "\e[031;1m12\e[0m) ???????????????????????????? (\e[34;1mauto-kill-user\e[0m)"
	echo -e "\e[031;1m13\e[0m) ?????????????????????????? (\e[34;1mbanned-user\e[0m)"
	echo -e "\e[031;1m14\e[0m) ??????????? (\e[34;1munbanned-user\e[0m)"
	echo -e "\e[031;1m15\e[0m) ????????? SSH & OpenVPN (\e[34;1muser-lock\e[0m)"
	echo -e "\e[031;1m16\e[0m) ???????????? SSH & OpenVPN yang terkunci (\e[34;1muser-unlock\e[0m)"
	echo -e "\e[031;1m17\e[0m) ????????????????????????????? ????? ????????? (\e[34;1mlog-limit\e[0m)"
	echo -e "\e[031;1m18\e[0m) ?????????????????????????????????????????? (\e[34;1mlog-ban\e[0m)"
    echo "=============================================="
	echo "??????????????? PPTP VPN??????????"
	echo -e "\e[031;1m19\e[0m) ??????????PPTP VPN (\e[34;1muser-add-pptp\e[0m)"
	echo -e "\e[031;1m20\e[0m) ??????? PPTP VPN (\e[34;1muser-delete-pptp\e[0m)"
	echo -e "\e[031;1m21\e[0m) ????????????????? PPTP VPN (\e[34;1mdetail-pptp\e[0m)"
	echo -e "\e[031;1m22\e[0m) ????????????????????? PPTP VPN (\e[34;1muser-login-pptp\e[0m)"
	echo -e "\e[031;1m23\e[0m) ??????????????? PPTP VPN (\e[34;1malluser-pptp\e[0m)"
	echo "=============================================="
	echo "??????????????? VPS???????????"
	echo -e "\e[031;1m24\e[0m) ????????????????????????(\e[34;1mauto-reboot\e[0m)"
	echo -e "\e[031;1m25\e[0m) ??????? (\e[34;1mcek-speedttes-vps\e[0m)"
	echo -e "\e[031;1m26\e[0m) ????????????????? (\e[34;1mps-mem\e[0m)"
	echo -e "\e[031;1m27\e[0m) ??????? Port OpenVPN  (\e[34;1mchange-openvpn-port\e[0m)"
	echo -e "\e[031;1m28\e[0m) ??????? Port Dropbear (\e[34;1mchange-dropbear-port\e[0m)"
	echo -e "\e[031;1m29\e[0m) ??????? Squid Port (\e[34;1mchange-squid-port\e[0m)"
	echo -e "\e[031;1m30\e[0m) ???????? OpenVPN (\e[34;1mrestart-openvpn\e[0m)"
	echo -e "\e[031;1m31\e[0m) ???????? Dropbear (\e[34;1mrestart-dropbear\e[0m)"
	echo -e "\e[031;1m32\e[0m) ???????? Squid (\e[34;1mrestart-squid\e[0m)"
	echo -e "\e[031;1m33\e[0m) ???????? Webmin (\e[34;1mrestart-webmin\e[0m)"
	echo -e "\e[031;1m34\e[0m) Benchmark (\e[34;1mbenchmark\e[0m)"
	echo -e "\e[031;1m35\e[0m) ??????????????? VPS (\e[34;1mpassword\e[0m)"
	echo -e "\e[031;1m36\e[0m) ???????????????? VPS (\e[34;1mhostname\e[0m)"
	echo -e "\e[031;1m37\e[0m) ????? Server (\e[34;1mreboot\e[0m)"
	echo "============================================="
	echo "Update Premium Script"
	echo -e "\e[031;1m38\e[0m) Update Now (\e[34;1mupdate\e[0m)"
	echo ""
	echo -e "\e[031;1m x\e[0m) ???"
	read -p "????????????????????????? ENTER: " option1
	case $option1 in
        1)  
            clear
            buatakun
            ;;
        2)  
            clear
            generate
            ;;
        3)	
            clear
            trial
			;;	
        4)
            clear
            userpass
            ;;
        5)
            clear
            userrenew
			;;
        6)
            userdelete
            ;;		
		7)
		    clear
	        userlogin
			;;
		8)
		    clear
			autolimit
			;;	
		9)
		    clear
            userdetail
            ;;
		10)
		    clear
            user-list
            ;;
        11)
               clear
               deleteuserexpire
	          ;;
	    12)
	          clear
	          #!/bin/bash
              # Created by http://www.sshinjector.net
              # Dilarang Keras Mengambil/mencuplik/mengcopy sebagian atau seluruh script ini.
              # Hak Cipta sshinjector.net (Dilindungi Undang-Undang nomor 19 Tahun 2002)
              red='\e[1;31m'
              green='\e[0;32m'
              NC='\e[0m'
              echo "Connecting to Third-vpn.net.."
              sleep 0.2
              echo "????????????..."
              sleep 0.3
              echo -e "${green}????????????????...${NC}"
              sleep 1
               echo""
	           echo "    AUTO KILL MULTI LOGIN    "    
	           echo "-----------------------------"
               autokilluser
               echo "-----------------------------"
               echo "AUTO KILL MULTI LOGIN FINISH"
               ;;
        13)
               clear
               userban
	          ;;
	    14)
               clear
               userunban
	          ;;
	    15)
	        clear
            userlock
			;;
		16)
		    clear
            userunlock
			;;
		17)
		    clear
		    loglimit
			;;
		18)
		    clear
            logban
			;;
	    19)
	        clear
            useraddpptp
			;;
		20)
		    clear
            userdeletepptp
			;;
	    21)
	        clear
            detailpptp
            ;;
        22)
            clear
            userloginpptp
			;;
		23)
		    clear
            alluserpptp
			;;
	    24)
	         clear
             autoreboot
            ;;
	    25)
	         clear
	         #!/bin/bash
            red='\e[1;31m'
            green='\e[0;32m'
            blue='\e[1;34m'
            NC='\e[0m'
            echo "Connecting to Third-vpn.net..."
            sleep 0.2
            echo "????????????..."
            sleep 0.3
            echo -e "${green}????????????????...${NC}"
            sleep 1
            echo""
            echo "????????????????"
            ./speedtest.py --share
            echo "????????????????????????? Script MoDiFy by THIRD-VPN"
            ;;
        26)
            free -m
            ;;
		27)	
		    clear
            echo "?? Port OpenVPN ??????????:"
            read -p "Port: " -e -i 1194 PORT
            sed -i "s/port [0-9]*/port $PORT/" /etc/openvpn/1194.conf
            service openvpn restart
            echo "OpenVPN ?????? : Port $PORT"
			;;
		28)	
		    clear
            echo "??? Port Dropbear ??????????:"
            read -p "Port: " -e -i 443 PORT
            sed -i "s/DROPBEAR_PORT=[0-9]*/DROPBEAR_PORT=$PORT/" /etc/default/dropbear
            service dropbear restart
            echo "Dropbear ?????? : Port $PORT"
			;;
        29)	
            clear
            echo "??? Port Squid ??????????:"
            read -p "Port: " -e -i 8080 PORT
            sed -i "s/http_port [0-9]*/http_port $PORT/" /etc/squid3/squid.conf
            service squid3 restart
            echo "echo "Squid3 ?????? : Port $PORT""
			;;			
        30)	
            clear
            echo "?????? Openvpn restart .................?????????"
            service openvpn restart
            echo "???????? OpenVPN ???????????? Script MoDiFy By THIRD-VPN"
			;;	
		31)
            clear
            echo "?????? dropbear restart .................?????????"
            service dropbear restart
            echo "???????? Dropbear ???????????? Script MoDiFy By THIRD-VPN"
            ;;
		32) 
		    clear
		    echo "?????? Squid restart .................?????????
			service squid3 restart
			echo "???????? OpenVPN ???????????? Script MoDiFy By THIRD-VPN"
			;;
		33)
		    clear
		    /etc/init.d/webmin restart
		    echo "???????? Webmin ???????????? Script MoDiFy By THIRD-VPN"
		    ;;
		34)
		    clear
            wget freevps.us/downloads/bench.sh -O - -o /dev/null|bash
           ;;
        35)
		    echo "???????????? VPS ????????????????? :"
		    passwd
			;;	
		36)
			echo "???? ??????? VPS ????????????????? :"
            echo "  ???????? : " hostname third 
            ;;
		37)
		    clear
			reboot
            ;;
        38)
            wget -O update https://raw.githubusercontent.com/cartoonn/openvpn-D7/master/config/update && chmod +x update && ./update
			;;
        x)
            ;;
        *) menu;;
    esac
