#!/bin/bash
# Created by http://www.sshinjector.net
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to Third-vpn.net.."
sleep 0.1
echo "กำลังตรวจสอบ..."
sleep 0.2
echo -e "${green}ได้รับอนุญาตแล้ว...${NC}"
sleep 0.5
echo""

if [ -f /etc/debian_version ]; then
	UIDN=1000
elif [ -f /etc/redhat-release ]; then
	UIDN=500
else
	UIDN=500
fi

echo "===============================================";
echo " "
echo "รายชื่อผู้ใช้ใน VPS:"
echo "(ชื่อผู้ใช้)    -     (วันหมดอายุ)  "
echo "-------------------------------"
ขณะอ่านรายการตรวจสอบ
do
        AKUN="$(echo $รายการตรวจสอบ | cut -d: -f1)"
        ID="$(echo $รายการตรวจสอบ | grep -v nobody | cut -d: -f3)"
        exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
        if [[ $ID -ge $UIDN ]]; then
        printf "%-17s %2s\n" "$AKUN" "$exp"
        fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= '$UIDN' && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
echo "-------------------------------"
echo " จำนวนบัญชี : $ผู้ใช้ทั้งหมด"
echo "-------------------------------"
echo " "
echo "===============================================";
