#!/bin/bash
# Created by http://www.sshinjector.net
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to third-vpn.net..."
sleep 0.2
echo "กำลังตรวจสอบ..."
sleep 0.3
echo -e "${green}ได้รับอนุญาตแล้ว...${NC}"
sleep 1
echo""

read -p "Masukkan ป้อนชื่อผู้ใช้ : " ชื่อผู้ใช้
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
echo "ชื่อผู้ใช้มีอยู่แล้วใน VPS ของคุณ"
exit 0
else
read -p "ใส่รหัสผ่าน [$username]: " รหัส
read -p "บัญชีที่ใช้งานระยะเวลา [$username] (วัน): " ระยะเวลาที่ใช้งาน
MYIP=$(wget -qO- ipv4.icanhazip.com)
today=`date +%s`
masa_aktif_detik=$(( $เวลาที่ใช้งาน * 86400 ))
saat_expired=$(($today + $masa_aktif_detik))
tanggal_expired=$(date -u --date="1970-01-01 $saat_expired sec GMT" +%Y/%m/%d)
tanggal_expired_display=$(date -u --date="1970-01-01 $saat_expired sec GMT" '+%d %B %Y')

echo "Connecting to third-vpn.net..."
sleep 0.4
echo "การสร้างบัญชี..."
sleep 0.3
echo "กำลังสร้างโฮสต์..."
sleep 0.2
echo "การสร้างชื่อผู้ใช้ใหม่ของคุณ: $ขื่อผู้ใช้"
sleep 0.2
echo "การสร้างรหัสผ่านสำหรับ $ชื่อผู้ใช้"
sleep 1


useradd $username
usermod -s /bin/false $username
usermod -e  $tanggal_expired $username
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  echo "Script by third-vpn.net"
  echo "ขอขอบคุณที่สมัครสมาชิก third-vpn.net"
  echo " "
  echo "สร้างบัญชีผู้ใช้ดังกล่าวแล้ว"
  echo "---------------------------------------"
  echo "   Host            : $MYIP"
  echo "   ชื่อผู้ใช้        : $ชื่อผู้ใช้"
  echo "   รหัสผ่าน        : $รหัสผ่าน"
  echo "   เวลาที่ใช้งาน      : $เวลา_วันที่ใช้งาน"
  echo "   วันหมดอายุ : $วันที่_แสดงวันหมดอายุ"
  echo "   Dropbear Port   : 80, 109, 110, 443"
  echo "   OpenSSH Port    : 22 , 143"
  echo "   Squid Proxy     : 8080, 8000, 3128"
  echo "   OpenVPN Config  : http://$MYIP:81/client.ovpn"
  echo "--------------------------------------"
  echo " "
fi