#!/bin/bash
# Created by http://www.sshinjector.net
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
echo "Connecting to third-vpn.net..."
sleep 0.2
echo "กำลังตรวจสอบ..."
sleep 0.3
echo -e "${green}ได้รับอนุญาตแล้ว...${NC}"
sleep 1

echo "โปรดรอสักครู่..."
sleep 0.5
echo "สร้างบัญชี..."
sleep 0.5
echo "กำลังสร้างโฮสต์..."
sleep 0.5
echo "กำลังสร้างชื่อผู้ใช้..."
sleep 0.5
echo "สร้างรหัสผ่าน..."
sleep 1
echo " "
MYIP=$(wget -qO- ipv4.icanhazip.com)
passrandom=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)

Login=trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`
masaaktif="1"
Pass=`</dev/urandom tr -dc a-f0-9 | head -c9`
IP=`dig +short myip.opendns.com @resolver1.opendns.com`
useradd -e `date -d "$วันที่ใช้งาน" +"%Y-%m-%d"` -s /bin/false -M $Login
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
  echo "Script by third-vpn.net"
  echo "ขอขอบคุณที่สมัครสมาชิก third-vpn.net"
  echo " "
  echo "รายละเอียดบัญชีทดลองใช้ของคุณ"
  echo "------------------------------"
  echo -e "Host/IP         : $MYIP"
  echo -e "Dropbear Port   : 80, 109, 110, 443"
  echo -e "OpenSSH Port    : 22 , 143"
  echo -e "Squid Proxy     : 8080, 8000, 3128"
  echo -e "OpenVPN Config  : http://$MYIP:81/client.ovpn"
  echo -e "ชื่อผู้ใช้        : $Login "
  echo -e "รหัสผ่าน        : $Pass\n" 
  echo -e "บัญชีนี้ใช้งานได้เพียง 1 วันเท่านั้น"
  echo "------------------------------"
  echo " "
